#!/bin/bash

# This is a thin wrapper around unobtanium-cli that strips the Windows-style EOLs
# from the output if present. It is necessary when using unobtanium-cli.exe on
# Linux since shells will interpret the line-endings as part of the result.

CURDIR=$(cd $(dirname "$0"); pwd)
# Get BUILDDIR and REAL_UNOBTANIUMD

# Grab the value of $REAL_UNOBTANIUMCLI which may be unobtanium-cli.exe.
. "${CURDIR}/tests-config.sh"

"${REAL_UNOBTANIUMCLI}" "$@" | sed 's/\r//'
